export type SCREENS_TYPE = {
  INTRODUCTION_SCREEN: undefined;
  HOME_SCREEN: undefined;
  LOGIN_SCREEN: undefined;
  REGISTER_SCREEN: undefined;
};

export enum SCREENS {
  INTRODUCTION_SCREEN = "INTRODUCTION_SCREEN",
  HOME_SCREEN = "HOME_SCREEN",
  LOGIN_SCREEN = "LOGIN_SCREEN",
  REGISTER_SCREEN = "REGISTER_SCREEN",
}
