export type SCREENS_TYPE = {
  INTRODUCTION_SCREEN: never;
  HOME_SCREEN: never;
  LOGIN_SCREEN: never;
  REGISTER_SCREEN: never;
  VERIFICATION_SCREEN: never;
  PHONE_SCREEN: never;
};

export enum SCREENS {
  INTRODUCTION_SCREEN = "INTRODUCTION_SCREEN",
  HOME_SCREEN = "HOME_SCREEN",
  LOGIN_SCREEN = "LOGIN_SCREEN",
  REGISTER_SCREEN = "REGISTER_SCREEN",
  PHONE_SCREEN = "PHONE_SCREEN",
  VERIFICATION_SCREEN = "VERIFICATION_SCREEN",
}
